// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3ocHskmtTLBE-QbCnMpciXTnyoKNhzoQ',
    appId: '1:461612285311:web:31613bb62996a981866e4a',
    messagingSenderId: '461612285311',
    projectId: 'medshelf-sunil',
    authDomain: 'medshelf-sunil.firebaseapp.com',
    storageBucket: 'medshelf-sunil.firebasestorage.app',
    measurementId: 'G-ZC7DXVE9RW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDalKpYZiwAiUOgC5802oE0MwrEkUFlThw',
    appId: '1:461612285311:android:e12e2dafbe9aac20866e4a',
    messagingSenderId: '461612285311',
    projectId: 'medshelf-sunil',
    storageBucket: 'medshelf-sunil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADEbiJ-nKijefFSQL4JSTmDAV8yQSdfwE',
    appId: '1:461612285311:ios:1a6a7b709c311359866e4a',
    messagingSenderId: '461612285311',
    projectId: 'medshelf-sunil',
    storageBucket: 'medshelf-sunil.firebasestorage.app',
    iosClientId: '461612285311-alai5jc2t9hnnkcl95p0bjbnopl9k2ee.apps.googleusercontent.com',
    iosBundleId: 'com.medshelf.medshelf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADEbiJ-nKijefFSQL4JSTmDAV8yQSdfwE',
    appId: '1:461612285311:ios:1a6a7b709c311359866e4a',
    messagingSenderId: '461612285311',
    projectId: 'medshelf-sunil',
    storageBucket: 'medshelf-sunil.firebasestorage.app',
    iosClientId: '461612285311-alai5jc2t9hnnkcl95p0bjbnopl9k2ee.apps.googleusercontent.com',
    iosBundleId: 'com.medshelf.medshelf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3ocHskmtTLBE-QbCnMpciXTnyoKNhzoQ',
    appId: '1:461612285311:web:34f7ccc29fe952ce866e4a',
    messagingSenderId: '461612285311',
    projectId: 'medshelf-sunil',
    authDomain: 'medshelf-sunil.firebaseapp.com',
    storageBucket: 'medshelf-sunil.firebasestorage.app',
    measurementId: 'G-BWG2957GFK',
  );
}
